name: Save Artifacts

on:
  # This file is reused, and called from other workflows
  workflow_call:

jobs:
  save-artifacts:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.repository_owner }} > wr_actions/ghowner.txt
          echo ${{ github.event.repository.name }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: artifact
          path: wr_actions
