---
name: Validate Examples

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/validate-examples.yaml'
      - 'examples/**'

concurrency:
  group: 'examples-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make validate-examples

  save-artifacts-on-fail:
    if: ${{ needs.validate-examples.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    if: ${{ needs.validate-examples.result }} == 'failure'
    uses: ./.github/workflows/comment-failure.yaml
